version: '3'

services:
  db:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: ungram
    ports:
      - 27017:27017
  backend:
    container_name: ungram-backend
    build:
      context: .
      dockerfile: docker/.dockerfile
    ports:
      - 8081:8081
    links:
      - db
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./docker/config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      monitoring:
        aliases:
          - prometheus
networks:
  monitoring:
