global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'sample_monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'ungram-backend:8081' ]
